- name: Deploy Ingress application
  template:
    src: ingress.yaml.j2
    dest: /tmp/ingress.yaml

- name: Apply the deployment file
  shell: |
    microk8s kubectl apply -f /tmp/ingress.yaml -n {{ namespace }}

- name: Deploy Ingress service
  template:
    src: ingress-service.yaml.j2
    dest: /tmp/ingress-service.yaml

- name: Apply the ingress service
  shell: |
    microk8s kubectl apply -f /tmp/ingress-service.yaml -n ingress

