- name: Install MicroK8s via snap
  snap:
    name: microk8s
    state: present
    classic: yes
  become: yes

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Set default policy for FORWARD chain to ACCEPT
  become: yes
  iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Enable necessary MicroK8s add-ons
  shell: |
    microk8s enable dns storage ingress

- name: Wait for MicroK8s to be ready
  shell: |
    microk8s status --wait-ready
